services:
  mysql:
    image: mysql:8.0
    container_name: ligue-lead-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ligue_lead_challenge
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: ligue-lead-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: ligue-lead-app
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ligue_lead_challenge
      DB_USER: root
      DB_PASS: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3000
    ports:
      - "5577:3000"
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data:
  redis_data:
  node_modules:
